// Code generated by hertz generator.

package admin

import (
	"buycar/biz/service"
	"context"

	admin "buycar/biz/model/admin"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// QueryAllConsults - 查询所有咨询记录
func QueryAllConsults(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.QueryAllConsultsReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 调用服务层处理业务逻辑
	adminService := &service.AdminService{}
	resp := adminService.QueryAllConsults(ctx)

	c.JSON(consts.StatusOK, resp)
}

// AdminAddUser - 添加用户
func AdminAddUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.AdminAddUserReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 调用服务层处理业务逻辑
	adminService := &service.AdminService{}
	resp := adminService.AdminAddUser(ctx, &req)

	c.JSON(consts.StatusOK, resp)
}

// AdminDeleteUser - 删除用户
func AdminDeleteUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.AdminDeleteUserReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 调用服务层处理业务逻辑
	adminService := &service.AdminService{}
	resp := adminService.AdminDeleteUser(ctx, &req)

	c.JSON(consts.StatusOK, resp)
}

// QueryFeedbackAnalysis - 查询用户反馈分析
func QueryFeedbackAnalysis(ctx context.Context, c *app.RequestContext) {
	var err error
	var req admin.QueryFeedbackAnalysisReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 调用服务层处理业务逻辑
	adminService := &service.AdminService{}
	resp := adminService.QueryFeedbackAnalysis(ctx)

	c.JSON(consts.StatusOK, resp)
}
